theme: jekyll-theme-midnight
title: "NFL Stats"
description: "Your one and only stop for NFL Stats."
gitorg: "https://github.com/STG-7/NFLStats-CPT-View"
description: "Your one and only stop for NFL Stats."
google_analytics:
